### ISSUE TITLE
字符覆盖程度如何？

### ISSUE THREAD

**Issue by CrotchBurnt** [GuiWonder/HuayingMincho#1]
请问 華英明朝 繁體 相比其他，文件容量明显更小，是缺失一些字符吗？

**Comment by GuiWonder** [comment]
您好，是的。由于简繁转换中存在一简对多繁的情况，为了能更好的实现简繁正确转换，在繁体版中加**入了大量的词汇信息**，而词汇需要占用字形空间，一个字体文件的字形数目**最多为 65535** 。因此在繁体版中采用了**移除一部分字形和简繁共用字形**的方法制作的。在繁体版中**汉字部分约一万六千**字符，不算少，基本满足日常使用。图中为 [CJK-character-count](https://github.com/NightFurySL2001/CJK-character-count) 软件对繁体版和传承版的汉字部分统计情况。

![hycountt](https://user-images.githubusercontent.com/55447192/185327845-e09b4fd7-1a10-4047-8086-8f3dda2dc873.png)  
![hycountcl](https://user-images.githubusercontent.com/55447192/185327969-b42e60c7-ea22-4d47-8071-8279633f990f.png)

**Comment by GuiWonder** [comment]
下一版将更换一简多繁的处理方式，不再使用伪字图作为词汇，因此不会有字符损失。

**Comment by GuiWonder** [comment]
新版繁体不再有字符损失，仍可处理一简多繁。
