### ISSUE TITLE
关于字形的问题

### ISSUE THREAD

**Issue by Steve-Yuu** [GuiWonder/HuayingMincho#2]
可以借助一点明朝的部分字图进行补充字体里面的一些简体字和部分字符
也可借助其修正某些部件的问题，比如“風”部件，可以借用一点明第三笔写横的（不针对所有版本），夜部件等
希望能采纳

**Comment by GuiWonder** [comment]
感谢建议！由于本项目字体继承了 [IPAmj明朝](https://moji.or.jp/mojikiban/font/)的很多功能，合并其他字体的字形时遇到一些困难。比如字形数目超过六万已接近一个字体的上限，以及 hinting、IVD 等问题。如果要加入更多字符，恐怕要破坏掉原本的一些功能（需要移除多版本字形、 hinting、IVD 等）。
当然也并非完全做不了，比如移除重要性不大的功能或制作另外一款衍生字体。附件中的测试字体是按照你所说的方法制作的字体（借用一点明“風”、“夜”部件，以及缺少的字符），未来可能使用这个方案。
[HuayingMinchoTesting.zip](https://github.com/GuiWonder/HuayingMincho/files/11116928/HuayingMinchoTesting.zip)

**Comment by ghost** [comment]
不建議使用一點明朝的簡體字，一點明朝的一些簡體字是個人新造的，像是新造了另一種簡體字，樣子非常奇怪且不美觀。

**Comment by GuiWonder** [comment]
> 不建議使用一點明朝的簡體字，一點明朝的一些簡體字是個人新造的，像是新造了另一種簡體字，樣子非常奇怪且不美觀。

新版的简体字基于[霞鹜新致宋](https://github.com/lxgw/LxgwNeoZhiSong)修改，对简体字用户来说应该不会有太多“奇怪”的感觉。
