### ISSUE TITLE
本字體個別字存在違和感

### ISSUE THREAD

**Issue by Steve-Yuu** [GuiWonder/HuayingMincho#3]
如題，本人已得知，本字體個別字符係霞鶩新緻宋借用，和原版IPA明朝相比，某些非簡體部件也做了符合《通規》風格的字形，但雖然説不能説非舊字形（諸如：“欠”部件）
<img width="224" alt="image" src="https://github.com/GuiWonder/HuayingMincho/assets/108906358/9f29db7d-6431-443b-aff9-2f723241fc65">
除此之外，像某些簡體字和簡體部首的斷筆處理，也是如此
還有有些字IPAMJ明朝原版太醜{像：“環”字沒有斷筆、“瓜”部件個別字符，以及某些朝鮮語用字“乙”、“〇”、“叱”在下的那些等等，地毯式搜索一時不大好整}
另外，一點明朝的話，可以酌情借用，建議借用某些非簡體字再略作魔改

**Comment by ghost** [comment]
千萬不要把字體做的怪模怪樣的。

**Comment by GuiWonder** [comment]
> 千萬不要把字體做的怪模怪樣的。

盡量。

**Comment by GuiWonder** [comment]
已更新，感謝您的反饋。
