### ISSUE TITLE
繁體中「饮」、「镇」使用了新字形

### ISSUE THREAD

**Issue by ghost** [GuiWonder/HuayingMincho#4]
繁體中「饮」、「镇」被轉換成了新字形「飲」、「鎮」，而舊版使用的是舊字形「飮」、「鎭」。建議使用舊字形。

**Comment by GuiWonder** [comment]
看來是新版新舊異體字分離引起的。

**Comment by ghost** [comment]
可否將其中一版的新舊異體字統一為舊字形？

**Comment by GuiWonder** [comment]
繁體版是基於傳承體修改，下一版考慮將傳承體的異體字統一爲舊字形。
